// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHomeCatalogus.Data;

#nullable disable

namespace MyHomeCatalogus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316144320_AddIdentitySchema")]
    partial class AddIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Barcode")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("barcode");

                    b.Property<string>("BarcodeMimeType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barcode_mime_type");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("picture");

                    b.Property<string>("PictureMimeType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("picture_mime_type");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<int>("PurchaseUnitId")
                        .HasColumnType("int")
                        .HasColumnName("purchaseunit_id");

                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("IX_products_producttypeid");

                    b.HasIndex("PurchaseUnitId");

                    b.HasIndex("StoreId");

                    b.HasIndex("Name", "StoreId")
                        .IsUnique()
                        .HasDatabaseName("UQ_products_name_store_id");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_barcode_mime_type_required", "(([barcode] IS NULL AND [barcode_mime_type] IS NULL) OR ([barcode] IS NOT NULL AND [barcode_mime_type] IS NOT NULL))");

                            t.HasCheckConstraint("CK_products_picture_mime_type_required", "(([picture] IS NULL AND [picture_mime_type] IS NULL) OR ([picture] IS NOT NULL AND [picture_mime_type] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ProductThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("PurchaseQuantity")
                        .HasColumnType("int")
                        .HasColumnName("purchase_quantity");

                    b.Property<int>("Threshold")
                        .HasColumnType("int")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_product_thresholds_product_id");

                    b.ToTable("product_thresholds", null, t =>
                        {
                            t.HasCheckConstraint("CK_productthresholds_purchasequantity_positive", "[purchase_quantity] > 0");

                            t.HasCheckConstraint("CK_productthresholds_threshold_zero_or_positive", "[threshold] >= 0");
                        });
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_product_types_name");

                    b.ToTable("product_types", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.PurchaseUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_purchaseunits_name");

                    b.ToTable("purchaseunits", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_recipes_name");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("fooproduct_Id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RecipeIngredientMeasurementId")
                        .HasColumnType("int")
                        .HasColumnName("measurement_id");

                    b.Property<int>("RecipePreparationStepId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_Preparationstep_Id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeIngredientMeasurementId");

                    b.HasIndex("RecipePreparationStepId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_recipe_ingredients_recipe_preparationstep_id_product_id");

                    b.ToTable("recipe_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_recipe_ingredients_quantity_positive", "[quantity] > 0");
                        });
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.RecipeIngredientMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique()
                        .HasDatabaseName("UQ_recipe_ingredient_measurements_abbreviation");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_recipe_ingredient_measurements_name");

                    b.ToTable("recipe_ingredient_measurements", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.RecipePreparationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int")
                        .HasColumnName("step_nr");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "StepNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_recipe_preparationsteps_recipe_id_step_nr");

                    b.ToTable("recipe_preparationsteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_recipe_preparationsteps_step_nr_positive", "[step_nr] > 0");
                        });
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_rooms_name");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("StorageUnitId")
                        .HasColumnType("int")
                        .HasColumnName("storageunit_id");

                    b.HasKey("Id");

                    b.HasIndex("StorageUnitId");

                    b.HasIndex("Name", "StorageUnitId")
                        .IsUnique()
                        .HasDatabaseName("UQ_shelves_name_storageunit_id");

                    b.ToTable("shelves", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CONVERT(date, GETDATE())");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .IsUnique()
                        .HasDatabaseName("UQ_shoppinglists_store_id_one_active_list")
                        .HasFilter("[is_completed] = 0");

                    b.ToTable("shoppinglists", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("int")
                        .HasColumnName("shoppinglist_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingListId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_shoppinglist_items_shoppinglist_id_product_id");

                    b.ToTable("shoppinglist_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_shoppinglist_items_quantity_positive", "[quantity] > 0");
                        });
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("ShelfId")
                        .HasColumnType("int")
                        .HasColumnName("shelf_id");

                    b.Property<int>("StockUnitId")
                        .HasColumnType("int")
                        .HasColumnName("stockunit_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_products_stockitems");

                    b.HasIndex("ShelfId");

                    b.HasIndex("StockUnitId");

                    b.HasIndex("ProductId", "ShelfId")
                        .IsUnique()
                        .HasDatabaseName("UQ_stockitems_productid_shelfid");

                    b.ToTable("stockitems", null, t =>
                        {
                            t.HasCheckConstraint("CK_stockitems_quantity_zero_or_positive", "[quantity] >= 0");
                        });
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StockItemAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("audit_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity_new");

                    b.Property<int>("OldQuantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity_old");

                    b.Property<int>("StockItemId")
                        .HasColumnType("int")
                        .HasColumnName("stockitem_id");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId")
                        .HasDatabaseName("IX_stockitem_audits_stockitem_id");

                    b.ToTable("stockitem_audits", null, t =>
                        {
                            t.HasCheckConstraint("CK_stockitem_audits_quantity_new_zero_or_positive", "[quantity_new] >= 0");

                            t.HasCheckConstraint("CK_stockitem_audits_quantity_old_zero_or_positive", "[quantity_old] >= 0");
                        });
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StockUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_stockunits_name");

                    b.ToTable("stockunits", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StorageUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("Name", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("UQ_storageunits_name_room_id");

                    b.ToTable("storageunits", (string)null);
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_stores_name");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyHomeCatalogus.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyHomeCatalogus.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHomeCatalogus.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyHomeCatalogus.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Product", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_product_types_products");

                    b.HasOne("MyHomeCatalogus.Shared.Domain.PurchaseUnit", "PurchaseUnit")
                        .WithMany()
                        .HasForeignKey("PurchaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_purchaseunits_products");

                    b.HasOne("MyHomeCatalogus.Shared.Domain.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_stores_products");

                    b.Navigation("ProductType");

                    b.Navigation("PurchaseUnit");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ProductThreshold", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.Product", "Product")
                        .WithOne()
                        .HasForeignKey("MyHomeCatalogus.Shared.Domain.ProductThreshold", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_thresholds_products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_products_recipe_ingredients");

                    b.HasOne("MyHomeCatalogus.Shared.Domain.RecipeIngredientMeasurement", "RecipeIngredientMeasurement")
                        .WithMany()
                        .HasForeignKey("RecipeIngredientMeasurementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_recipe_ingredient_measurements_recipe_ingredients");

                    b.HasOne("MyHomeCatalogus.Shared.Domain.RecipePreparationStep", "RecipePreparationStep")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipePreparationStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_recipe_preparationsteps_recipe_ingredients");

                    b.Navigation("Product");

                    b.Navigation("RecipeIngredientMeasurement");

                    b.Navigation("RecipePreparationStep");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.RecipePreparationStep", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.Recipe", "Recipe")
                        .WithMany("PreparationSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_recipe_preparationsteps_recipes");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Shelf", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.StorageUnit", "StorageUnit")
                        .WithMany("Shelves")
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_shelves_storageunits");

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ShoppingList", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_stores_shoppinglists");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_products_shoppinglist_items");

                    b.HasOne("MyHomeCatalogus.Shared.Domain.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_shoppinglist_items_shoppinglists");

                    b.Navigation("Product");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StockItem", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.Product", "Product")
                        .WithMany("StockItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_products_stockitems");

                    b.HasOne("MyHomeCatalogus.Shared.Domain.Shelf", "Shelf")
                        .WithMany("StockItems")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_shelves_stockitems");

                    b.HasOne("MyHomeCatalogus.Shared.Domain.StockUnit", "StockUnit")
                        .WithMany()
                        .HasForeignKey("StockUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_stockunits_stockitems");

                    b.Navigation("Product");

                    b.Navigation("Shelf");

                    b.Navigation("StockUnit");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StockItemAudit", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.StockItem", "StockItem")
                        .WithMany()
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_stockitem_audits_stockitems");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StorageUnit", b =>
                {
                    b.HasOne("MyHomeCatalogus.Shared.Domain.Room", "Room")
                        .WithMany("StorageUnits")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_storageunits_rooms");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Product", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Recipe", b =>
                {
                    b.Navigation("PreparationSteps");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.RecipePreparationStep", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Room", b =>
                {
                    b.Navigation("StorageUnits");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.Shelf", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("MyHomeCatalogus.Shared.Domain.StorageUnit", b =>
                {
                    b.Navigation("Shelves");
                });
#pragma warning restore 612, 618
        }
    }
}
